AWSTemplateFormatVersion: '2010-09-09'
Description: 'Indigo Platform - ElastiCache Redis Cluster'

Parameters:
  VPCStackName:
    Type: String
    Default: indigo-vpc
  Environment:
    Type: String
    Default: production
  NodeType:
    Type: String
    Default: cache.t4g.micro
    AllowedValues:
      - cache.t4g.micro
      - cache.t4g.small
      - cache.r6g.large

Resources:
  # Security Group for Redis
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ElastiCache Redis
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPCId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub 'indigo-${Environment}-redis-sg'

  # Subnet Group
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Redis
      SubnetIds:
        - Fn::ImportValue: !Sub '${VPCStackName}-PrivateSubnet1Id'
        - Fn::ImportValue: !Sub '${VPCStackName}-PrivateSubnet2Id'

  # Redis Replication Group
  RedisCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: Indigo Redis Cluster
      Engine: redis
      EngineVersion: '7.0'
      CacheNodeType: !Ref NodeType
      NumCacheClusters: 2
      AutomaticFailoverEnabled: true
      MultiAZEnabled: true
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds:
        - !Ref RedisSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub 'indigo-${Environment}-redis'

Outputs:
  RedisEndpoint:
    Description: Redis Primary Endpoint
    Value: !GetAtt RedisCluster.PrimaryEndPoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-RedisEndpoint'

  RedisPort:
    Description: Redis Port
    Value: !GetAtt RedisCluster.PrimaryEndPoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-RedisPort'

  RedisSecurityGroupId:
    Description: Redis Security Group ID
    Value: !Ref RedisSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-RedisSecurityGroupId'
